import { NextRequest, NextResponse } from 'next/server';
import bcrypt from 'bcryptjs';
import QRCode from 'qrcode';
import connectDB from '@/lib/mongodb';
import User from '@/models/User';
import { registerSchema } from '@/lib/validations/auth';
import { checkRateLimit } from '@/lib/redis-rate-limit';
import { sanitizeInput } from '@/lib/security';
import { sendWelcomeEmail } from '@/lib/email';

export async function POST(req: NextRequest) {
  try {
    // Rate limiting for registration
    const rateLimitResult = await checkRateLimit(req, {
      maxRequests: 5, // 5 registration attempts per 15 minutes
      windowMs: 15 * 60 * 1000,
    });
    if (!rateLimitResult.allowed) {
      return rateLimitResult.response;
    }

    // Parse and validate request body
    const body = await req.json();
    const validationResult = registerSchema.safeParse(body);

    if (!validationResult.success) {
      const errors = validationResult.error.issues.map((err) => ({
        field: String(err.path.join('.')),
        message: err.message,
      }));
      
      return NextResponse.json(
        { 
          success: false,
          error: 'Validation failed',
          details: errors,
        },
        { status: 400 }
      );
    }

    const { userType, name, companyName, email, phone, password } = validationResult.data;

    await connectDB();

    // Check for existing user (case-insensitive)
    const existing = await User.findOne({ email: email.toLowerCase() });
    if (existing) {
      return NextResponse.json(
        { success: false, error: 'Email already in use' },
        { status: 409 }
      );
    }

    // Hash password with appropriate cost factor
    const passwordHash = await bcrypt.hash(password, 12);

    const user = await User.create({
      userType,
      name: userType === 'individual' && name ? sanitizeInput(name) : undefined,
      companyName: userType === 'company' && companyName ? sanitizeInput(companyName) : undefined,
      email: email.toLowerCase(),
      phone: phone ? sanitizeInput(phone) : undefined,
      passwordHash,
      role: 'user',
    });

    // Generate and store QR code for the user (MANDATORY - MUST match publicId)
    // publicId is generated by the pre-save hook, so it should always exist
    if (!user.publicId || user.publicId.trim() === '') {
      console.error('Error: publicId was not generated during user creation');
      await User.findByIdAndDelete(user._id);
      return NextResponse.json(
        { success: false, error: 'Registration failed. Please try again.' },
        { status: 500 }
      );
    }

    // QR code generation is MANDATORY for every user
    let qrDataUrl: string;
    try {
      // Get origin from request URL (most reliable) or use production URL
      // QR codes should always point to production, not localhost
      let origin: string;
      try {
        const requestUrl = new URL(req.url);
        // Only use request URL if it's not localhost (production/staging)
        if (!requestUrl.hostname.includes('localhost') && !requestUrl.hostname.includes('127.0.0.1')) {
          origin = `${requestUrl.protocol}//${requestUrl.host}`;
        } else {
          // In development, use production URL for QR codes (they're immutable)
          origin = process.env.NEXT_PUBLIC_APP_URL || process.env.NEXTAUTH_URL || 'https://adoptrees.com';
        }
      } catch {
        // Fallback to environment variable or production URL
        origin = process.env.NEXT_PUBLIC_APP_URL || process.env.NEXTAUTH_URL || 'https://adoptrees.com';
      }
      
      // Ensure we never use localhost in QR codes (they're immutable and should work in production)
      if (origin.includes('localhost') || origin.includes('127.0.0.1')) {
        origin = 'https://adoptrees.com';
      }
      
      const qrUrl = `${origin}/u/${user.publicId.toLowerCase()}`;
      // Use same settings as modal (width: 320 for better quality)
      qrDataUrl = await QRCode.toDataURL(qrUrl, { 
        width: 320,
        margin: 1,
        errorCorrectionLevel: 'M'
      });
      
      // Validate QR code was generated
      if (!qrDataUrl || qrDataUrl.trim() === '') {
        throw new Error('QR code generation returned empty result');
      }
    } catch (qrError) {
      // QR code generation failure MUST fail registration since it's mandatory
      console.error('Error generating QR code during registration:', qrError);
      // Delete the user if QR code generation fails
      await User.findByIdAndDelete(user._id);
      return NextResponse.json(
        { success: false, error: 'Registration failed. Please try again.' },
        { status: 500 }
      );
    }

    // Save QR code (immutable after this)
    try {
      user.qrCode = qrDataUrl;
      await user.save();
      
      // Final verification: Ensure QR code was saved
      const savedUser = await User.findById(user._id).select('qrCode publicId').lean() as { qrCode?: string; publicId?: string } | null;
      if (!savedUser || !savedUser.qrCode || savedUser.qrCode.trim() === '') {
        throw new Error('QR code was not saved to database');
      }
      if (!savedUser.publicId || savedUser.publicId !== user.publicId) {
        throw new Error('publicId mismatch after save');
      }
    } catch (saveError) {
      // If save fails, delete the user
      console.error('Error saving QR code during registration:', saveError);
      await User.findByIdAndDelete(user._id);
      return NextResponse.json(
        { success: false, error: 'Registration failed. Please try again.' },
        { status: 500 }
      );
    }

    // Send welcome email (don't fail registration if email fails)
    try {
      const userName = userType === 'individual' ? name : companyName;
      await sendWelcomeEmail(user.email, userName || '', userType);
    } catch (emailError) {
      // Log error but don't fail registration if email sending fails
      console.error('Error sending welcome email during registration:', emailError);
    }

    return NextResponse.json(
      {
        success: true,
        data: {
          id: user._id,
          email: user.email,
        },
      },
      { status: 201 }
    );
  } catch (_err) {
    
    // Don't expose internal errors
    return NextResponse.json(
      { success: false, error: 'Registration failed. Please try again later.' },
      { status: 500 }
    );
  }
}


